name: python_autotest_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pytest
  - selenium
  - pip
  - pip:
    - webdriver-manager
variables:
  browser: "chrome"
  Browser.Version: "120.0"
  Python.Version: "3.13"